<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Class Namespace
    |--------------------------------------------------------------------------
    |
    | This value sets the root namespace for Livewire component classes to be
    | used when generating fully qualified class names from relative class names.
    | It will also inform `artisan` commands where to make stubs.
    |
    */

    'class_namespace' => 'App\\Livewire',

    /*
    |--------------------------------------------------------------------------
    | View Path
    |--------------------------------------------------------------------------
    |
    | This value is used to generate view paths for your Livewire components. If
    | you need to change where the views are located, you may specify an
    | alternate value here.
    |
    */

    'view_path' => resource_path('views/livewire'),

    /*
    |--------------------------------------------------------------------------
    | Layout
    |--------------------------------------------------------------------------
    |
    | The view that will be used as the layout when rendering a single component
    | as a full page. You can also use different layouts for different routes
    | by using the `Layout` attribute on your Livewire component.
    |
    */

    'layout' => 'layouts.app',

    /*
    |--------------------------------------------------------------------------
    | Lazy Loading Placeholder
    |--------------------------------------------------------------------------
    |
    | The "lazy" loading containers generated by Livewire will be filled with
    | this view on initial page load. You are free to create your own view
    | and specify its path here if you'd like to customize the look & feel.
    |
    */

    'lazy_placeholder' => null,

    /*
    |--------------------------------------------------------------------------
    | Morphs
    |--------------------------------------------------------------------------
    |
    | Class aliases for use in Livewire component references.
    |
    */

    'morphs' => [
        'auth.logout' => \App\Livewire\Auth\Logout::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Temporary File Uploads
    |--------------------------------------------------------------------------
    |
    | Livewire handles file uploads by storing uploads in a temporary directory
    | before the a component's `save` method is called. All file uploads are
    | automatically deleted after an upload is finished.
    |
    */

    'temporary_file_upload' => [
        'disk' => 'local',
        'directory' => 'livewire-tmp',
        'rules' => 'required|file|max:12288', // 12 MB max
        'directory_visibility' => 'private',
    ],

    /*
    |--------------------------------------------------------------------------
    | Livewire Assets
    |--------------------------------------------------------------------------
    |
    | When serving Livewire's JavaScript and CSS from CDNs, the URLs will be
    | generated using these URIs. Typically these will be the same, except for
    | the `js` URL, which includes a `@if(config('app.debug'))..@endif` block
    | to serve unminified assets in development.
    |
    */

    'asset_url' => null,

    'app_url' => null,

    /*
    |--------------------------------------------------------------------------
    | Middleware (available from Laravel 9 onwards)
    |--------------------------------------------------------------------------
    |
    | You can enable or disable Livewire in your application by attaching
    | middleware to every Livewire request.
    |
    */

    'middleware_group' => 'web',

    'middleware' => [],

    /*
    |--------------------------------------------------------------------------
    | Query String
    |--------------------------------------------------------------------------
    |
    | Livewire supports making your component properties available as query
    | string parameters. Tou may specify the max. depth of nesting allowed in
    | case of complex data structures.
    |
    */

    'query_string' => [
        'enabled' => true,
        'exclude' => [],
        'path' => null,
        'nesting_depth' => 5,
    ],

    /*
    |--------------------------------------------------------------------------
    | Security
    |--------------------------------------------------------------------------
    |
    | This value may be used to add additional security to outgoing Livewire
    | requests using Laravel's AES-128-CBC / AES-256-GCM encryption ciphers.
    |
    */

    'security' => [
        'obfuscate_bindings' => env('LIVEWIRE_OBFUSCATE_BINDINGS', true),
    ],

    'inject_assets' => true,

    /*
    |--------------------------------------------------------------------------
    | Auto-inject Livewire's Update Script
    |--------------------------------------------------------------------------
    |
    | By default, Livewire automatically injects its JavaScript for you on every
    | page that includes a Livewire component. If you'd prefer to manually
    | include the JavaScript yourself, you can set this to false.
    |
    */

    'inject_morph_markers' => true,

    'navigate' => [
        'enabled' => true,
        'show_progress_bar' => true,
        'progress_bar_color' => '#fff',
    ],

    /*
    |--------------------------------------------------------------------------
    | Render On Redirect
    |--------------------------------------------------------------------------
    |
    | This value determines if Livewire should re-render a component after a
    | redirect has been performed. This is useful if you want to ensure that
    | the component state is fresh after a redirect.
    |
    */

    'render_on_redirect' => false,

];
